apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  source:
    chart: jetstack/cert-manager
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://charts.jetstack.io
    targetRevision: 1.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true