apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: cattle-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: rancher-stable/rancher
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.5.7
  syncPolicy:
    automated:
      prune: true
      selfHeal: true